intermediate_items:
  WAFFENGRIFF:
    item:
      material: "BREEZE_ROD"
      name: "<red>Waffengriff</red>"
      lore:
        - "<gray>Dies ist ein Waffengriff</gray>"
      sign: "WAFFENGRIFF"
      placeable: false
    recipe:
      shape:
        - " A "
        - " B "
        - " C "
      ingredients:
        A: "COPPER_INGOT"
        B: "BLAZE_ROD"
        C: "IRON_INGOT"
      amount: 1
plugin_items:
  LAUTE:
    recipe:
      shape:
        - "   "
        - " A "
        - "   "
      ingredients:
        A: "WAFFENGRIFF"